### ISSUE TITLE
setOptions issues

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-tutorials#6]
- setting signers doesn't work
- setting inflation destination doesn't work

**Comment by bartekn** [comment]
The problem is with a deploy. I've just confirmed it's working locally (was able to submit [a transaction with inflation dest change](https://horizon-testnet.stellar.org/operations/182660664135681)). @irisli can you look at this?

**Comment by jedmccaleb** [comment]
Deploy network explorer to github pages

**Comment by bartekn** [comment]
Moved Network Explorer to Github pages. @nullstyle can you make these repos public?
https://github.com/stellar/xdr-debugger
https://github.com/stellar/network-explorer

**Comment by jedmccaleb** [comment]
done. but I renamed to xdr-viewer

**Comment by bartekn** [comment]
:+1:

**Comment by jedmccaleb** [comment]
are these published?

**Comment by bartekn** [comment]
http://stellar.github.io/network-explorer/ is working. Not sure why http://stellar.github.io/xdr-viewer/ is not there. Can you make me an admin of this repo so I can check settings? Or can you check "Github pages" section in xdr-viewer settings?

**Comment by jedmccaleb** [comment]
Iris: can you change the links to these in the devportal

**Comment by bartekn** [comment]
Here are the links:
* http://stellar.github.io/xdr-viewer/
* http://stellar.github.io/network-explorer/

**Comment by irisli** [comment]
I've fixed the links. Looks like this has been resolved
