### ISSUE TITLE
reimagine network explorer

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-tutorials#7]
It needs to be redesigned.
There should be three sections I think:
1) account creation/saving section
2) a transaction builder section. allows you to add a string of operations. Ideally would show the js of the tx being built.
3) a transaction signing section. allows you to add a string of signers. can either pull in the tx_blob from step 2 or paste in one.
4) allow you to make all API calls to horizon section. Should show the Curl of the horizon call.

**Comment by jedmccaleb** [comment]
deliverables: wire frame

**Comment by irisli** [comment]
this is the first iteration
